config/routes.rb
Rails.application.routes.draw do

  # devise_for :agencies
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :orders

  # Agency Pages
  Rails.application.routes.draw do
    devise_for :agency, controllers: {
      sessions: 'agency/sessions',
      passwords: 'agency/passwords',
      registrations: 'agency/registrations',
      confirmations: 'agency/confirmations',
      unnlocks: 'agency/unlocks'
    }
  end

  get 'agency/:id/inbox', to: "agency_panel#inbox", :as => :agency_inbox
  get 'agency-request-account', to: 'shyft_pages#agency_request_account', :as => :agency_account

  # root 'shyft_pages#home'
  root 'shyft_pages#home'

  # Static Pages for the Site
  get 'invite'              => 'shyft_pages#request_invite'
  get 'how-to-hire'         => 'shyft_pages#how_to_hire'
  get 'how-to-work'         => 'shyft_pages#how_to_work'
  get 'why-shyft'           => 'shyft_pages#why_shyft'
  get 'home-alternate'      => 'shyft_pages#home_alternate'
  get 'cphollister'         => 'shyft_pages#cphollister_profile'
  get 'book_cphollister'    => 'shyft_pages#cphollister_booking'
  get 'create_event'    => 'shyft_pages#create_event'
  get 'confirm_booking'     => 'shyft_pages#confirmation'
  get 'agency_waitlist'     => 'shyft_pages#agency_waitlist'
  get 'agency_request_account'  => 'shyft_pages#agency_request_account'
  get 'error_booking'       => 'shyft_pages#booking_error'
  get 'check_email'         => 'ambassadors#check_email'
  get 'agency_waitlist'     => 'shyft_pages#agency_waitlist'

  # Legal Pages
  get 'terms-of-use',         to: 'legal_docs#terms_of_use'
  get 'privacy-policy',       to: 'legal_docs#privacy_policy'
  get 'event-rules',          to: 'legal_docs#event_rules'
  get 'cancellation-policy',  to: 'legal_docs#cancellation_policy'
  get 'refund-policy',        to: 'legal_docs#refund_policy'

  # Ambassador Specific Pages
  get 'ambassadors_signup' => 'ambassadors#new'
  get 'ambassadors_search', to: 'ambassadors#index'

  # Ambassador Session Specific Pages
  get 'ambassador_sessions/new'
  get 'login'       => 'ambassador_sessions#new'
  post 'login'      => 'ambassador_sessions#create'
  delete 'logout'   => 'ambassador_sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'

  get 'password_resets/new'
  get 'ambassador_password_reset' =>'password_resets#reset'

  # For error pages
  %w( 404 422 500 503 ).each do |code|
    get code => "errors#show", :code => code
  end
  # Form emailing

  # Twilio Phone Verification
  resources :phone_numbers, only: [:new, :create]
  post 'phone_numbers/verify' => "phone_numbers#verify"

  resources :images

  # Session Specific Pages
  get 'sessions/new'

  resources :ambassadors
  resources :line_items
  resources :carts
  resources :ambassador_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :order,     except: :index
  resources :contacts, only: [:new, :create]
  resources :bookings, only:[:new, :create, :edit, :index, :show, :update] do
    member do
      get :book_request_accept_confirm
      get :book_request_decline_confirm
    end
  end

  # resources :agency do
  resources :events, only: [:new, :create, :edit, :index, :show, :update] do
    resources :event_locations, only: [:new, :create, :update]
    resources :conversations, only:[:index]
  end
  delete "/events/:id", to: "events#destroy", as: "delete_event"
  get 'events/shortList', to: 'events#shortList'
  get 'new_event_session', to: 'events#new_event_session'

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
  get 'contacts' => 'contacts#new'
  post 'contacts' => 'contacts#create'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  #Ambassador Dashboard
  get 'dashboard', to: 'dashboard#index'
  post 'dashboard/cancel_booking', to: 'dashboard#cancel_booking', as: :cancel_booking

  #Ambassador Busy Shifts
  get 'busyShifts', to:'busy_shift#index'
  get 'busyShifts/new', to: 'busy_shift#new', as: 'new_busy_shift'
  post 'busyShifts', to: 'busy_shift#create', as: 'busy_shifts'
  get 'busyShifts/:id/edit', to: 'busy_shift#edit', as: 'edit_busy_shifts'
  patch 'busyShift/:id', to: 'busy_shift#update'
  delete 'busyShift/:id', to: 'busy_shift#destroy'

  #Creating Shifts and Roles from Event Dates
  get 'roleTypes/', to: 'shifts_role#roleTypes'
  get 'roleStatusList/', to: 'shifts_role#roleStatusList'
  get 'shiftsByDate/', to: 'shifts_role#shiftsByDate'
  get 'rolesByShift/', to: 'shifts_role#rolesByShift'
  post 'shifts/create', to: 'shifts_role#createShift'
  post 'shifts/createRole', to: 'shifts_role#createRoleForShift'
  patch 'shifts/role/:role_id', to: 'shifts_role#changeRoleForShift'
  delete 'shifts/:shift_id', to: 'shifts_role#destroyShift'
  delete 'roles/:role_id', to: 'shifts_role#destroyRole'

  patch 'shortList/add', to: 'shifts_role#shortList'
  delete 'shortList/removeAmbassador', to: 'shifts_role#remove_ambassador_from_short_list'

  get 'shortList/book', to: 'short_lists#submit'

  #Event Dates
  get 'eventDate', to: 'event_dates#datesByLocation'
  get 'eventDate/shifts', to: 'event_dates#shiftsByDateId'
  get 'eventDate/new', to: 'event_dates#new', as: 'new_event_dates'
  post 'eventDate/create', to: 'event_dates#create', as: 'event_dates'
  patch 'eventDate/:id', to: 'event_dates#update'
  delete 'eventDate/id', to: 'event_dates#destroy'

  #Fake Filter Query
  get 'test', to: 'filter_ambassadors#test'
  get 'filterAmbassadors/', to: 'filter_ambassadors#filter'
  get 'filterAmbassadorsIndex/', to: 'filter_ambassadors#filter_index'
  get 'filterForRole/', to: 'filter_ambassadors#fitler_by_role'
  get 'getShortListedAmbassadors/', to: 'filter_ambassadors#short_listed_ambassadors'

  namespace :api, defaults: {format: :json} do
    resources :events, only: [:update, :new, :index, :create, :show, :destroy]
    resources :event_locations, only: [:create, :new, :update, :index, :show, :destroy]
    resources :event_dates, only: [:create, :new, :update, :index, :show, :destroy]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :logged_in_ambassador,  only: [:edit, :update]
  before_action :correct_user,          only: [:edit, :update]
  helper_method :ambassador_conversation

  #get all events confirmed by ambassador...
  def index
  	if logged_in?
      #for current events we're not checking status
      current_event_ids = EventRole.joins('join event_dates ON event_roles.event_date_id=event_dates.id').where('role_status =? and ambassador_id=? and event_date >=  NOW()::date',STATUS_CONFIRMED, current_user.id).pluck(:event_id)
      #for past events we only check confiremd events
	  	past_event_ids =  EventRole.joins('join event_dates ON event_roles.event_date_id=event_dates.id').where('role_status=? and ambassador_id=? and event_date < NOW()::date',STATUS_CONFIRMED, current_user.id).pluck(:event_id)
	  	@current_events = Event.where(id: current_event_ids)
      @past_events = Event.where(id: past_event_ids)
	  else
	  	@current_events = nil
      @past_events = nil
	  end
    render :index
  end


  def cancel_booking
    event = Event.find(params[:event_id])
    ambassador = Ambassador.find(params[:ambassador_id])

    pending_roles = EventRole.where('event_id = ? AND ambassador_id = ? AND role_status = ?', event.id, ambassador.id, STATUS_PENDING)

    #cancel all pending bookings
    booking_staff_items = BookingStaffItem.where(event_role_id: pending_roles.pluck(:id))
    booking_staffs = BookingStaff.where(id: booking_staff_items.pluck(:booking_staff_id))
    bookings = Booking.where(id: booking_staffs.pluck(:booking_id))
    
    booking_staff_items.update_all(status: STATUS_CANCELLED)
    booking_staffs.update_all(confirm_token: nil)
    pending_roles.update_all(role_status: STATUS_EMPTY)
    #cancel all confirmed but not started bookings
    confirmed_roles = EventRole.joins('JOIN event_dates ON event_roles.event_date_id = event_dates.id').where('event_id = ? AND ambassador_id = ? AND role_status = ? and event_dates.event_date >= NOW()::date', event.id, ambassador.id, STATUS_CONFIRMED)


    booking_staff_items = BookingStaffItem.where(event_role_id: confirmed_roles.pluck(:id))
    booking_staffs = BookingStaff.where(id: booking_staff_items.pluck(:booking_staff_id))
    bookings = Booking.where(id: booking_staffs.pluck(:booking_id))
    agency =  event.agency #Agency.where(id: bookings.pluck(:agency_id)).first


    booking_staff_items.update_all(status: STATUS_CANCELLED)
    booking_staffs.update_all(confirm_token: nil)
    confirmed_roles.update_all(role_status: STATUS_EMPTY)

    #cancel all short list bookings
    short_listed_roles = EventRole.where('event_id = ? AND ambassador_id = ? AND role_status = ?', event.id, ambassador.id, STATUS_SHORT_LIST)

    booking_staff_items = BookingStaffItem.where(event_role_id: short_listed_roles.pluck(:id))
    booking_staffs = BookingStaff.where(id: booking_staff_items.pluck(:booking_staff_id))
    bookings = Booking.where(id: booking_staffs.pluck(:booking_id))

    booking_staff_items.update_all(status: STATUS_CANCELLED)
    booking_staffs.update_all(confirm_token: nil)
    short_listed_roles.update_all(role_status: STATUS_EMPTY)

    # notify globally via email
    BookingMailer.send_email_booking_cancelled_notification(event ,ambassador, agency).deliver_now
    
    # notify agency via email
    BookingMailer.send_email_booking_cancelled_agency(event ,ambassador, agency).deliver_now
    #now redirect to index
    if agency
      flash[:cancel_booking] = "Your booking has been cancelled! A message has been sent to the #{agency.display_name} to notify them."
    else
      flash[:cancel_booking] = "NO Agency found"
    end  
    
    redirect_to action: 'index'
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_cancel_booking.html.erb
<!-- Modal -->
<div id="cancel_booking<%=event.id%>" class="modal fade cancel-booking" role="dialog">
  <div class="modal-dialog">
  <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" align="center"><%= event.name %></h4>
      </div> <!-- modal-header -->
      <%= form_tag cancel_booking_path do %>
      <%= hidden_field_tag 'event_id', event.id %>
      <%= hidden_field_tag 'ambassador_id', current_user.id %>
      <div class="modal-body">
        <div class="form">
          <div class="panel-body align-center">
            <p>By cancelling this event your ambassador rating will be reduced making it less likely to get more bookings. Please try to  message agency to resolve any issue you might have before cancelling.</p>
          </div>

          <div class="panel-title align-center">
            <h4 class="modal-title">Are you sure that you want to cancel this event?</h4>
          </div>
        </div> <!-- form -->
      </div> <!-- modal-body -->
      <div class="modal-footer">
        <a type="button" class="no-cancel" data-dismiss="modal">No, don't cancel</a>
        <%= submit_tag 'Cancel Event', class:'cancel-button' %>
      </div>
      <% end %>
    </div> <!-- modal-content -->
  </div> <!-- modal-dialog -->
</div> <!-- End of Modal-->

app/views/dashboard/_event_panel.html.erb
<div class="panel-body">
    <div class="col-sm-12">
      <div class="table-responsive">
        <table class="table table-hover">
          <% if events.present? %>
            <thead>
              <tr>
                <th>Start Date</th>
                <th>Event Name</th>
                <th>Earnings</th>
                <th>Messages</th>
                <% if show_cancel %>
                <th>Cancel Event</th>
                <% end %>
              </tr>
            </thead>
            <tbody>
              <% events.each do |e| %>
                <tr>
                <% if e.event_locations == [] %>
                  <td>-</td>
                <% else %>
                  <% event_dates = e.event_locations.first.event_dates.order(:event_date).first(1) %>
                  <td>
                    <% if event_dates.present? && event_dates.first.event_date.present? %>
                      <%= event_dates.first.event_date.strftime("%A,  %B %d, %Y") %>
                    <% end %>  
                    </td>
              	<% end %>
                  <td class='edit-link'>
                    <% if e.name == nil %>
                      <p>Unknown Event</p>
                    <% else %>
                      <%= link_to e.name.capitalize, '#', data: {target: "#eventDetail#{e.id}", toggle: "modal" } %>
                      <%= render 'events/event_detail', {event: e} %>
                    <% end %>
                  </td>
                  <td><%= number_to_currency(e.total_earning_by(current_user.id)) %></td>
                  <td>
                    <%= link_to conversation_messages_path(e.conversations.involving_ambassador(current_user).last) do %>
                      <i class="fa fa-envelope"></i>
                      <% if e.total_unread_messages_by_ambassador(current_user) > 0 %>
                              <sup class="unread-messages"><%= e.total_unread_messages_by_ambassador(current_user)%></sup>
                            <% end %>
                    <% end %>
                  </td>
                  <% if show_cancel %>
                  <td>
                    <%= link_to 'javascript:void(0)', data: {target: "#cancel_booking#{e.id}", toggle: "modal"}, type: 'button' do %>
                        Cancel
                      <% end %>
                      <%= render 'cancel_booking', {event: e } %>  
                  </td>
                  <% end %>
                </tr>
              <%end%>
            </tbody>
          </table>
          <% else %>
          <table>
            <thead>
              <tr>
                <th>
                <p>Looks like you don't have any new booking request. Feel free to adjust you account settings.</p>
                </th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
        <% end %>
      </div> <!-- /.table-responsive -->
    </div> <!-- panel -->
  </div> <!-- col -->

app/views/dashboard/index.html.erb
<div class="account-settings row">
  <div class="content row">
    <div class="main row"><br />
      <% flash.each do |name, msg| %>
      	<%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <div class="title">
        <h2>Dashboard</h2>
      </div>
      <div id="exTab2" class="container"> 
        <ul class="nav nav-tabs">
            <li class="active">
              <a  href="#1" data-toggle="tab">Current Events</a>
            </li>
            <li><a href="#2" data-toggle="tab">Past Events</a>
            </li>
            
        </ul>

        <div class="tab-content ">
          <div class="tab-pane active" id="1">
            <%= render partial:'event_panel', locals: {events: @current_events, show_cancel: true} %>
          </div>
          <div class="tab-pane" id="2">
            <%= render partial:'event_panel', locals: {events: @past_events, show_cancel: false} %>
          </div>
          
        </div>
      </div> <!-- tab view -->
    </div> <!-- main -->
  </div> <!-- content -->
</div> <!-- account-settings -->

app/views/dashboard/show.html.erb
<div class="account-settings row">
  <div class="content row">
    <div class="main row"><br />
      <div class="title">
        <h2><%= @event.name %></h2>
      </div>

			<div class="panel panel-default">	
				<div class="panel-body">
					<div class="row">
						<div class="col-sm-2">
							<h4>Details:</h4>
						</div>
						<div class="col-sm-10">
							<p><%= @event.event_details %></p>
						</div>
					</div>
					<% for event_location in @event.event_locations %>
						<div class="row">
							<div class="col-sm-6">
								<div class="col-sm-4">
									<h4>Locations:</h4>
								</div>
								<div class="col-sm-8">
									<h4><%= event_location.label %></h4>
									<p><b>Address:</b> <%= event_location.address %>, <%= event_location.state %>, <%= event_location.zip %> <%= event_location.country %></p>
									<p><b>Notes:</b> <%= event_location.notes %></p>
								</div> <!-- col -->
							</div> <!-- col -->
							<div class="col-sm-6">
								<% for event_date in event_location.event_dates %>
									<div class="col-sm-4">
										<h4>Dates:</h4>
									</div> <!-- col -->
									<div class="col-sm-8">
										<% if event_date.event_date.present? %>
											<h4><%= event_date.event_date.strftime("%A, %B, %e") %></h4>
										<% end %>
										<% if event_date.start_time.present? && event_date.end_time.present? %>
											<p><%= event_date.start_time.strftime("%k%P") %> to <%= event_date.end_time.strftime("%k%P") %></p>
										<% end %>
									</div>
							</div> <!-- col -->
						</div> <!-- row -->
						<% for event_role in event_date.event_roles %>
							<div class="row">
								<div class="col-sm-2">
									<h4>Roles</h4>
								</div>
								<div class="col-sm-10">
									<div class="col-sm-2">
										<p><%= event_role.role.capitalize %></p>
									</div>
									<div class="col-sm-5">
										<b>Rate: $</b><%= event_role.hourly_rate %>/hr</p>
									</div>
									<div class="col-sm-5">
										<b>Quantity: </b><%= event_role.quantity %></p>
									</div>
								</div>
							</div>
							<% end %>
							<% end %>
						</div>
						<% end %>

						<br><%= link_to 'Edit', edit_event_path(@event) %>
						<br><%= link_to 'View All', events_path(params[:agency_id]) %>
					</div>	
				</div>	
				<div class="row">
					<h3>Requests sent</h3>
					<hr>
				</div>
				<div class="row">
					<h3>Matched Ambassadors</h3>
					<hr>
					<% @ambassadors.order(:created_at).each do |ambassador| %>
						<% if ambassador.images[0] && ambassador.activated == true %>
						<div class="col-sm-4">
							<div class="thumbnail text-center">
								<%= link_to attachment_image_tag(ambassador.profile_photo, :file, :fill, 500, 500, class: 'img-responsive'), ambassador%>	
									<div class="details text-center">
										<h3 id="name-link">
											<%= link_to ambassador.first_name.capitalize, ambassador %>
											<%= link_to ambassador.last_name.capitalize, ambassador %>
										</h3>
										<div class="basic"><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
											</div>
										<div class="secondary"><strong>Rate:</strong> $<%= number_with_precision(ambassador.rate.to_f, precision: 0) %></div> 
											<%= button_to 'Request to Book', line_items_path(ambassador_id: ambassador), class: "btn btn-primary" %>
									</div> <!-- details -->
								</div> <!-- box -->
							</div>
						<% end %>
					<% end %>
				</div> <!-- panel-body -->
			</div> <!-- panel -->


    </div> <!-- main -->
  </div> <!-- content -->
</div> <!-- agency -->