config/routes.rb
Rails.application.routes.draw do

  # devise_for :agencies
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :orders

  # Agency Pages
  Rails.application.routes.draw do
    devise_for :agency, controllers: {
      sessions: 'agency/sessions',
      passwords: 'agency/passwords',
      registrations: 'agency/registrations',
      confirmations: 'agency/confirmations',
      unnlocks: 'agency/unlocks'
    }
  end

  get 'agency/:id/inbox', to: "agency_panel#inbox", :as => :agency_inbox
  get 'agency-request-account', to: 'shyft_pages#agency_request_account', :as => :agency_account

  # root 'shyft_pages#home'
  root 'shyft_pages#home'

  # Static Pages for the Site
  get 'invite'              => 'shyft_pages#request_invite'
  get 'how-to-hire'         => 'shyft_pages#how_to_hire'
  get 'how-to-work'         => 'shyft_pages#how_to_work'
  get 'why-shyft'           => 'shyft_pages#why_shyft'
  get 'home-alternate'      => 'shyft_pages#home_alternate'
  get 'cphollister'         => 'shyft_pages#cphollister_profile'
  get 'book_cphollister'    => 'shyft_pages#cphollister_booking'
  get 'create_event'    => 'shyft_pages#create_event'
  get 'confirm_booking'     => 'shyft_pages#confirmation'
  get 'agency_waitlist'     => 'shyft_pages#agency_waitlist'
  get 'agency_request_account'  => 'shyft_pages#agency_request_account'
  get 'error_booking'       => 'shyft_pages#booking_error'
  get 'check_email'         => 'ambassadors#check_email'
  get 'agency_waitlist'     => 'shyft_pages#agency_waitlist'

  # Legal Pages
  get 'terms-of-use',         to: 'legal_docs#terms_of_use'
  get 'privacy-policy',       to: 'legal_docs#privacy_policy'
  get 'event-rules',          to: 'legal_docs#event_rules'
  get 'cancellation-policy',  to: 'legal_docs#cancellation_policy'
  get 'refund-policy',        to: 'legal_docs#refund_policy'

  # Ambassador Specific Pages
  get 'ambassadors_signup' => 'ambassadors#new'
  get 'ambassadors_search', to: 'ambassadors#index'

  # Ambassador Session Specific Pages
  get 'ambassador_sessions/new'
  get 'login'       => 'ambassador_sessions#new'
  post 'login'      => 'ambassador_sessions#create'
  delete 'logout'   => 'ambassador_sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'

  get 'password_resets/new'
  get 'ambassador_password_reset' =>'password_resets#reset'

  # For error pages
  %w( 404 422 500 503 ).each do |code|
    get code => "errors#show", :code => code
  end
  # Form emailing

  # Twilio Phone Verification
  resources :phone_numbers, only: [:new, :create]
  post 'phone_numbers/verify' => "phone_numbers#verify"

  resources :images

  # Session Specific Pages
  get 'sessions/new'

  resources :ambassadors
  resources :line_items
  resources :carts
  resources :ambassador_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :order,     except: :index
  resources :contacts, only: [:new, :create]
  resources :bookings, only:[:new, :create, :edit, :index, :show, :update] do
    member do
      get :book_request_accept_confirm
      get :book_request_decline_confirm
    end
  end

  # resources :agency do
  resources :events, only: [:new, :create, :edit, :index, :show, :update] do
    resources :event_locations, only: [:new, :create, :update]
    resources :conversations, only:[:index]
  end
  delete "/events/:id", to: "events#destroy", as: "delete_event"
  get 'events/shortList', to: 'events#shortList'
  get 'new_event_session', to: 'events#new_event_session'

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
  get 'contacts' => 'contacts#new'
  post 'contacts' => 'contacts#create'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  #Ambassador Dashboard
  get 'dashboard', to: 'dashboard#index'
  post 'dashboard/cancel_booking', to: 'dashboard#cancel_booking', as: :cancel_booking

  #Ambassador Busy Shifts
  get 'busyShifts', to:'busy_shift#index'
  get 'busyShifts/new', to: 'busy_shift#new', as: 'new_busy_shift'
  post 'busyShifts', to: 'busy_shift#create', as: 'busy_shifts'
  get 'busyShifts/:id/edit', to: 'busy_shift#edit', as: 'edit_busy_shifts'
  patch 'busyShift/:id', to: 'busy_shift#update'
  delete 'busyShift/:id', to: 'busy_shift#destroy'

  #Creating Shifts and Roles from Event Dates
  get 'roleTypes/', to: 'shifts_role#roleTypes'
  get 'roleStatusList/', to: 'shifts_role#roleStatusList'
  get 'shiftsByDate/', to: 'shifts_role#shiftsByDate'
  get 'rolesByShift/', to: 'shifts_role#rolesByShift'
  post 'shifts/create', to: 'shifts_role#createShift'
  post 'shifts/createRole', to: 'shifts_role#createRoleForShift'
  patch 'shifts/role/:role_id', to: 'shifts_role#changeRoleForShift'
  delete 'shifts/:shift_id', to: 'shifts_role#destroyShift'
  delete 'roles/:role_id', to: 'shifts_role#destroyRole'

  patch 'shortList/add', to: 'shifts_role#shortList'
  delete 'shortList/removeAmbassador', to: 'shifts_role#remove_ambassador_from_short_list'

  get 'shortList/book', to: 'short_lists#submit'

  #Event Dates
  get 'eventDate', to: 'event_dates#datesByLocation'
  get 'eventDate/shifts', to: 'event_dates#shiftsByDateId'
  get 'eventDate/new', to: 'event_dates#new', as: 'new_event_dates'
  post 'eventDate/create', to: 'event_dates#create', as: 'event_dates'
  patch 'eventDate/:id', to: 'event_dates#update'
  delete 'eventDate/id', to: 'event_dates#destroy'

  #Fake Filter Query
  get 'test', to: 'filter_ambassadors#test'
  get 'filterAmbassadors/', to: 'filter_ambassadors#filter'
  get 'filterAmbassadorsIndex/', to: 'filter_ambassadors#filter_index'
  get 'filterForRole/', to: 'filter_ambassadors#fitler_by_role'
  get 'getShortListedAmbassadors/', to: 'filter_ambassadors#short_listed_ambassadors'

  namespace :api, defaults: {format: :json} do
    resources :events, only: [:update, :new, :index, :create, :show, :destroy]
    resources :event_locations, only: [:create, :new, :update, :index, :show, :destroy]
    resources :event_dates, only: [:create, :new, :update, :index, :show, :destroy]
  end
end

app/controllers/shyft_pages_controller.rb
class ShyftPagesController < ApplicationController

  before_filter :disable_nav, only: [:alt_home, :request_invite]

  def request_invite
  end

  def home
    @agency_logged_in = !current_agency.nil?
  end

  def how_to_hire
  end

  def how_to_work
  end

  def why_shyft
  end

  def ambassadors
  end

  def cphollister_profile
  end

  def cphollister_booking
  end

  def confirmation
  end

  def agency_request_account
  end
end

app/helpers/shyft_pages_helper.rb
module ShyftPagesHelper
end

app/views/shyft_pages/_how_background.html.erb
<div class="row">
	<div class="how-background">
	  <div class="hiw-layer">
	    <div class="how-header">
	      <div class="title">
	        <h1>Hire Ambassadors</h1>
	      </div> <!-- title -->
	      <div class="subheader">
	        <h4>Learn how to get reliable ambassadors for your event</h4>
	      </div> <!-- subheader -->
	    </div> <!-- how-header -->
	  </div> <!-- hiw-layer -->
	</div> <!-- how-background -->
</div> <!-- row -->

app/views/shyft_pages/agency_request_account.html.erb
<% provide(:title, 'New Agency Account Requested') %>
<% provide(:description, "Get an account to be able to book local, reliable ambassadors for your events.") %>
<div class="container-fluid login">
  <div class="background">
    <div class="row">
      <div class="check-email">
        <div class="text-center hiw-icon">
          <i class="fa fa-thumbs-o-up fa-5x"></i>
        </div>
        <div class="title">
          <% provide(:title, 'Shyft') %>
          <h3>SUCCESS!</h4>
        </div>

        <div class="instructions">
          <p>Your request for an Agency account was sent!</p>
          <p>We will contact you within 24 hours to activate it.</p>
        </div>
      </div> <!-- check-email -->
    </div> <!-- row -->
  </div> <!-- background -->
</div> <!-- container -->

app/views/shyft_pages/booking_error.html.erb
<% provide(:title, 'Booking Error') %>

<div class="container-fluid login"> 
  <div class="background">
    <div class="row">    
      <div class="check-email">
<% params[:flash].each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>                
        <div class="text-center hiw-icon">
          <i class="fa fa-exclamation fa-5x"></i>
        </div>
        <div class="title">
          <% provide(:title, 'Shyft') %>
          <h3>PAYMENT ERROR!</h4>
        </div>

        <div class="instructions">
          <p>Sorry, there was a problem processing your payment.</p>
          <p>Please check the payment information you provided and try again.</p>
          <p>If you continue to experience problems making booking requests contact bookings@shyftworks.com.</p>	
        </div>
      </div> <!-- check-email -->
    </div> <!-- row -->
  </div> <!-- background -->

app/views/shyft_pages/cphollister_booking.html.erb
<% provide(:title, 'Booking') %>

<div class="booking">
	<div class="background">
		<div class="content row">
			<div class="col-sm-8 primary">
				<div class="payment row">
					<div class="title row">
						<div class="col-sm-12">
							<h2>Payment</h2>
						</div>
					</div>
					<div class="name row">
						<div class="col-sm-5">
							<input type="text" class="form-control" placeholder="Name on card" size="40x1">
						</div>
					</div>
					<div class="card-number row">
						<div class="col-sm-5">
							<input type="text" class="form-control" placeholder="16 digit card number" size="20x1">
						</div>
						<div class="col-sm-5">	
				        <select class="form-control">
									<option>Visa</option>
									<option>MasterCard</option>
									<option>American Express</option>
								</select>
							</div>
					</div>
					<div class="authentication row">
							<div class="col-sm-5">
				        <select class="form-control left">
									<option>January - 01</option>
									<option>February - 02</option>
									<option>March - 03</option>
								</select>
							</div>
							<div class="col-sm-3">	
				        <select class="form-control">
									<option>2015</option>
									<option>2016</option>
									<option>2017</option>
								</select>
							</div>
							<div class="col-sm-2">
								<input type="text" class="form-control" placeholder="CVC" size="6x1">
							</div>
					</div>
				</div> <!-- payment -->
				<hr>
				<div class="billing row">
					<div class="title row">
						<div class="col-sm-12">
							<h2>Billing Details</h2>
						</div>
					</div>
					<div class="company row">
						<div class="col-sm-8">
							<input type="text" class="form-control" placeholder="Company name" size="40x1">
						</div>
					</div>
					<div class="address_1 row">
						<div class="col-sm-8">
							<input type="text" class="form-control" placeholder="Address 1" size="40x1">
						</div>
					</div>
					<div class="address_2 row">
						<div class="col-sm-8">
							<input type="text" class="form-control" placeholder="Address 2" size="40x1">
						</div>
					</div>
					<div class="authentication row">
						<div class="col-sm-5">
							<input type="text" class="form-control" placeholder="City" size="40x1">
						</div>
						<div class="col-sm-3">
			        <select class="form-control">
								<option>ON</option>
								<option>AB</option>
								<option>QC</option>
							</select>
						</div>
						<div class="col-sm-3">	
			        <select class="form-control">
								<option>Canada</option>
								<option>United States</option>
								<option>United Kingdom</option>
							</select>
						</div>
					</div>
				</div> <!-- Billing -->	
				<hr>
				<div class="terms row">
					<div class="col-sm-12">
						<p>By clicking on "Request to Book", you agree to pay the total amount shown, which includes Service Fees, on the right and to the <a href="#">Terms of Service</a>, <a href="#">Event Rules</a>, C<a href="#">ancellation Policy</a> and <a href="#">Agency Refund Policy</a>.</p>
					</div>
				</div>				
				<div class="book-button row">
					<div class="col-sm-12">
						<%= link_to(confirmation_path, class: 'btn btn-lg', id: 'book-btn') do %>
						 	<i class="fa fa-bolt"></i> Request to Book
						<% end %>
					</div>
				</div> <!-- book-button -->
				<div class="response row">
					<div class="col-sm-12">
						<p>They'll have 24 hours to reply. You will only be charged if the ambassador accepts your request. If the ambassador declines or does not respond, no charge is made.</p>
					</div>
				</div>
			</div> <!-- col-sm-8 -->

			<div class="col-sm-4 secondary">
				<div class="invoice row">
					<%= link_to image_tag("cphollister/8.jpg", alt: "CPHollister 1", class: "img-responsive"), cphollister_profile_path %>
					<div class="box">
						<div class="profile row">
							<div class="col-sm-12">
								<h4>Chris Hollister</h4>
								<select class="form-control">
									<option>Molson Sampling</option>
									<option>RBC Handout</option>
									<option>Canadian Tire</option>
									<option>Nestle Chocolate</option>
								</select>
							</div> <!-- col-sm-6 -->
						</div> <!-- profile -->
						<hr>
						<div class="dates">
							<div class="row">
								<div class="col-sm-12">
									<span><p><b>Start: </b>Sat, Dec 20, 2014 9:00am<p></span>
									<span><p><b>End: </b>Sat, Dec 20, 2014 5:00pm</p></span>
								</div>
							</div> <!-- col-sm-5 -->
						</div>
						<hr>
						<div class="agree">
							<div class="policy row">
								<div class="type col-sm-7">
									<p>Cancellation Policy</p>
								</div> <!-- col-sm-7 -->
								<div class="details col-sm-5">
									<p><a href="#">12 hour</a></p>
								</div> <!-- col-sm-5 -->
							</div> <!-- policy -->
							<div class="policy row">
								<div class="type col-sm-7">
									<p>Event Policy</p>
								</div> <!-- col-sm-7 -->
								<div class="details col-sm-5">
									<p><a href="#">Review</a></p>
								</div> <!-- col-sm-5 -->
							</div> <!-- policy -->
						</div> <!-- agree -->
						<hr>
						<div class="summary">
							<div class="line-item row">
								<div class="details col-sm-7">
									<p>$<span>18 <sup>CAD</sup> x 8 hours</span></p>
								</div> <!-- col-sm-6 -->
								<div class="sub-total col-sm-5">
									<p>$<span>144 <sup>CAD</sup></p>
								</div> <!-- col-sm-6 -->
							</div> <!-- line-item -->
							<div class="line-item row">
								<div class="details col-sm-7">
									<p>Service Fee <i class="fa fa-question-circle"></i></p>
								</div> <!-- col-sm-6 -->
								<div class="sub-total col-sm-5">
									<p>$<span>17 <sup>CAD</sup></p>
								</div> <!-- col-sm-6 -->
							</div> <!-- line-item -->
						</div> <!-- total -->
						<hr>
						<div class="total row">
							<div class="details col-sm-7">
								<p>Total</p>
							</div> <!-- col-sm-6 -->
							<div class="sub-total col-sm-5">
								<p>$<span>161 <sup>CAD</sup></p>
							</div> <!-- col-sm-6 -->
						</div> <!-- line-item -->
					</div> <!-- box -->
				</div> <!-- invoice -->
			</div> <!-- col-sm-4 -->
		</div> <!-- content -->
	</div> <!-- background -->
</div> <!-- booking -->


<% if notice %>
<p id="notice"><%= notice %></p> <% end %>
<h2>Your Pragmatic Cart</h2> 
<ul>
	<% @cart.line_items.each do |item| %> 
		<li><%= item.ambassador.first_name %></li>
	<% end %> 
</ul>

app/views/shyft_pages/home.html.erb
<% provide(:title, "Shyft: Brand Ambassadors, Promo Models & Event Staff") %>
<% provide(:description, "Hire reliable ambassadors in Toronto Canada with Shyft.") %>
<div class="home">
  <div class="main-background row">
    <div class="layer">
      <div class="homepage-header">
        <div class="title row">
          <h1>Hire Reliable Ambassadors</h1>
        </div> <!-- title -->
<!--         <div class="subheader">
          <h3>Hire reliable brand ambassadors in Toronto Canada.</h3>
        </div> <! subheader -->
        <div class="main-cta row">
          <div class="row">
            <%= button_to('How It Works', how_to_work_path, :class => 'btn btn-lg', :id => 'how-btn', :method => :get) %>
          </div>
        </div> <!-- main-cta -->

        <div class="searchLayer row">
          <div class="search-bar row">
              <div class="col-sm-4 item">
                <div class="option">
                  <select class="form-control">
                    <option>Toronto, ON Canada</option>
                  </select>
                </div> <!-- option -->
              </div> <!-- col-sm-4 -->

            <%= form_tag('/ambassadors_search', method: :get, :class => "form-inline") do %>
              <div class='col-sm-7 item'>
                <div class="form-group">
                  <div class="col-sm-4 sub-item" id="startTimeInput">
                    <%= text_field_tag(:start_time, params[:start_time], placeholder: "Start Time", class: "time start form-control", required: true  ) %>
                  </div>
                  <div class="col-sm-4 sub-item" id="endTimeInput">
                  <%= text_field_tag(:end_time, params[:end_time], placeholder: "End Time", class: "time end form-control", required: true  ) %>
                  </div>
                  <div class="col-sm-4  sub-item">
                    <div class='input-group date' id='datetimepicker1' />
                      <%= text_field_tag(:event_date, params[:event_date], placeholder: "Date", class: "form-control", required: true  ) %>
                      <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                      </span>
                    </div> <!-- date -->

                    <script type="text/javascript">
                      var nowDate = new Date();
                      var today = new Date(nowDate.getFullYear(), nowDate.getMonth(), nowDate.getDate(), 0, 0, 0, 0);
                        $(function () {
                            $('#datetimepicker1').datetimepicker({
                              format: "MMM DD, YYYY",
                              defaultDate: nowDate,
                              minDate: today
                            });
                            $("#datetimepicker1").on("dp.change", function (e) {

                            });

                           // initialize input widgets first
                           $('#startTimeInput .time').timepicker({
                               'showDuration': true,
                               'timeFormat': 'h:i A',
                               'scrollDefault': 'now'
                           });

                            // initialize input widgets first
                           $('#endTimeInput .time').timepicker({
                               'showDuration': true,
                               'timeFormat': 'h:i A',
                               'scrollDefault': 'now'
                           });

                          $('#startTimeInput .time').on("selectTime", function (e) {
                            // remove current end time and update with new values
                            $('#endTimeInput .time').timepicker('remove');
                              var starttime = $('#startTimeInput .time').val()
                              var startdate = $('#startTimeInput .time').timepicker('getTime')
                              var end_time_minimum = String(startdate.getHours() + 1) + ":" + String(startdate.getMinutes())
                               $('#endTimeInput .time').timepicker({
                                  'showDuration': true,
                                  'timeFormat': 'h:i A',
                                  'scrollDefault': 'now',
                                  'disableTimeRanges': [["12:00 am", end_time_minimum]],
                                  'minTime': starttime
                              })
                          });
                      });

                    </script>
                  </div>
                </div> <!-- form-group -->
              </div> <!-- col -->
              <div class="col-sm-1 item">
                <div class="option">
                  <%= submit_tag "Find", :class => 'btn btn-md', id: 'btn-search' %>
                </div> <!-- option -->
              </div> <!-- col-sm-3 -->
          </div> <!-- search-bar -->
        </div> <!-- searchLayer -->
        <% end %>
      </div> <!-- homepage-header -->
    </div> <!-- layer -->
  </div> <!-- main-backround -->

  <div class="why-shyft text-center row">
    <div class="why-container">
      <div class="why-heading">
        <h1>Why Shyft</h1>
      </div>
      <div class="col-sm-4 reason-box">
        <div class="why-icon">
          <!-- <i class="fa fa-search-plus fa-5x"></i> -->
          <%= image_tag "shyft-search-circle.png", class: 'img-responsive' %>
        </div> <!-- icon -->
        <div class="why-title">
          <h3>The Most Powerful Ambassador Search</h3>
        </div> <!-- title -->
        <div class="why-details">
          <p>Filter by availability, repeat hires, response time, ratings, proximity to event location and more...</p>
        </div> <!-- details -->
      </div> <!-- col -->
      <div class="col-sm-4 reason-box">
        <div class="why-icon">
          <!-- <i class="fa fa-shield fa-5x"></i> -->
          <%= image_tag "shyft-reliable-circle.png", class: 'img-responsive text-center' %>
        </div> <!-- icon -->
        <div class="why-title">
          <h3>Proven & Reliable<br> Staff</h3>
          </div> <!-- title -->
        <div class="why-details">
          <p>Get to know great ambassadors through timeliness tracking, performance reviews and ratings.</p>
        </div> <!-- details -->
      </div> <!-- col -->
      <div class="col-sm-4 reason-box">
        <div class="why-icon">
          <%= image_tag "shyft-instabook-circle.png", class: 'img-responsive' %>
          <!-- <i class="fa fa-bolt fa-5x"></i> -->
        </div> <!-- icon -->
        <div class="why-title">
          <h3>Fast, Easy <br> Bookings</h3>
        </div> <!-- title -->
        <div class="why-details">
          <p>From a single interface you can schedule, screen and book ambassadors for your event shifts.</p>
        </div> <!-- details -->
      </div> <!-- col -->
    </div> <!--  -->
  </div> <!-- why-shyft -->

  <div class="home-signups text-center row">
    <div class="signup-container">
      <div class="col-sm-6 agency-call">
        <div class="split">
          <div class="title">
            <h1>I'm looking for staff.</h1>
          </div> <!--  -->
          <div class="call-to-action">
            <div class="col-sm-6 learn">
              <p>
                <%= link_to '> Learn More', how_to_hire_path %>
              </p>
            </div>
            <div class="col-sm-6 action">
              <% if @agency_logged_in %>
                <%= link_to new_event_session_path, method: :get do %>
                  <i class="fa fa-calendar"></i> Create Event
                <% end %>
              <% else %>
                <%= link_to new_agency_registration_path do %>
                  <i class="fa fa-calendar"></i> Create Event
                <% end %>
              <% end %>


            </div> <!-- col -->
          </div> <!-- call -->
        </div> <!-- split -->
      </div> <!-- col -->
      <div class="col-sm-6 ambassador-call">
        <div class="split">
          <div class="title">
            <h1>I want to work!</h1>
          </div> <!--  -->
          <div class="call-to-action">
            <div class="col-sm-6 learn">
              <p>
                <%= link_to '> Learn More', how_to_work_path %>
              </p>
            </div> <!-- col -->
            <div class="col-sm-6 action">
              <%= link_to ambassadors_signup_path do %>
                <i class="fa fa-user"></i> Get Profile
              <% end %>
            </div> <!-- col -->
          </div> <!-- call -->
        </div> <!-- split -->
      </div> <!-- col -->
    </div> <!-- signup-container -->
  </div> <!-- home-signups -->
</div>

app/views/shyft_pages/request_invite.html.erb
<div class="home">
  <div class="main-background row">
    <nav class="navbar" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand" id="shyft-logo">
            <%= link_to image_tag("shyft-logo-white.png", alt: "Shyft logo"), root_path, id: "logo" %>
          </div>
        </div> <!-- navbar-header -->
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        </div><!-- navbar-collapse -->
      </div><!-- container-fluid -->
    </nav>
    <div class="homepage-header">
      <div class="title">
        <h1>Become an Event Ambassador</h1>
      </div> <!-- title -->
      <!-- <div class="subheader">
        <h3>Control your profile and get paid within 24 hours.</h3>
      </div> <!-- subheader -->
      <div class="main-cta">
        <div class="row">

          <!-- Begin MailChimp Signup Form -->
          <div id="mc_embed_signup">
            <form action="//startupsalesmachine.us8.list-manage.com/subscribe/post?u=69893f396eba396da977a10a0&amp;id=dcec54c2aa" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                <div id="mc_embed_signup_scroll">

            <div class="row">
              <div class="mc-field-group col-md-6">
                <input type="email" value="" name="EMAIL" class="required email form-control" id="mce-EMAIL">
              </div>
              <div class="col-md-6">
                <div id="mce-responses" class="clear">
                  <div class="response" id="mce-error-response" style="display:none"></div>
                  <div class="response" id="mce-success-response" style="display:none"></div>
                </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                  <div style="position: absolute; left: -5000px;"><input type="text" name="b_69893f396eba396da977a10a0_dcec54c2aa" tabindex="-1" value=""></div>
                  <div class="clear"><input type="submit" value="REQUEST INVITATION" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
                  </div>
                </div>
              </div>
            </form>
          </div>

          <!--End mc_embed_signup-->


        </div> <!-- row -->
      </div> <!-- main-cta -->
    </div> <!-- homepage-header -->
  </div> <!-- main-backround -->


  <div class="home-footer row">
    <nav class="navbar" role="navigation">
      <div class="container home-copyright-nav">
        <div class="col-sm-12 copyright-text text-right">
          <ul class="nav nav-pills nav-justified copyright-link navbar-right">
              &copy; 2014 Shyft Inc. All Rights Reserved. <%= link_to "Terms", terms_of_use_path %> | <%= link_to "Privacy", privacy_policy_path %>
          </ul>
        </div> <!-- copyright-text -->
      </div> <!-- container -->
    </nav>
  </div> <!-- main-footer -->