config/routes.rb
Rails.application.routes.draw do

  # devise_for :agencies
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :orders

  # Agency Pages
  Rails.application.routes.draw do
    devise_for :agency, controllers: {
      sessions: 'agency/sessions',
      passwords: 'agency/passwords',
      registrations: 'agency/registrations',
      confirmations: 'agency/confirmations',
      unnlocks: 'agency/unlocks'
    }
  end

  get 'agency/:id/inbox', to: "agency_panel#inbox", :as => :agency_inbox
  get 'agency-request-account', to: 'shyft_pages#agency_request_account', :as => :agency_account

  # root 'shyft_pages#home'
  root 'shyft_pages#home'

  # Static Pages for the Site
  get 'invite'              => 'shyft_pages#request_invite'
  get 'how-to-hire'         => 'shyft_pages#how_to_hire'
  get 'how-to-work'         => 'shyft_pages#how_to_work'
  get 'why-shyft'           => 'shyft_pages#why_shyft'
  get 'home-alternate'      => 'shyft_pages#home_alternate'
  get 'cphollister'         => 'shyft_pages#cphollister_profile'
  get 'book_cphollister'    => 'shyft_pages#cphollister_booking'
  get 'create_event'    => 'shyft_pages#create_event'
  get 'confirm_booking'     => 'shyft_pages#confirmation'
  get 'agency_waitlist'     => 'shyft_pages#agency_waitlist'
  get 'agency_request_account'  => 'shyft_pages#agency_request_account'
  get 'error_booking'       => 'shyft_pages#booking_error'
  get 'check_email'         => 'ambassadors#check_email'
  get 'agency_waitlist'     => 'shyft_pages#agency_waitlist'

  # Legal Pages
  get 'terms-of-use',         to: 'legal_docs#terms_of_use'
  get 'privacy-policy',       to: 'legal_docs#privacy_policy'
  get 'event-rules',          to: 'legal_docs#event_rules'
  get 'cancellation-policy',  to: 'legal_docs#cancellation_policy'
  get 'refund-policy',        to: 'legal_docs#refund_policy'

  # Ambassador Specific Pages
  get 'ambassadors_signup' => 'ambassadors#new'
  get 'ambassadors_search', to: 'ambassadors#index'

  # Ambassador Session Specific Pages
  get 'ambassador_sessions/new'
  get 'login'       => 'ambassador_sessions#new'
  post 'login'      => 'ambassador_sessions#create'
  delete 'logout'   => 'ambassador_sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'

  get 'password_resets/new'
  get 'ambassador_password_reset' =>'password_resets#reset'

  # For error pages
  %w( 404 422 500 503 ).each do |code|
    get code => "errors#show", :code => code
  end
  # Form emailing

  # Twilio Phone Verification
  resources :phone_numbers, only: [:new, :create]
  post 'phone_numbers/verify' => "phone_numbers#verify"

  resources :images

  # Session Specific Pages
  get 'sessions/new'

  resources :ambassadors
  resources :line_items
  resources :carts
  resources :ambassador_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :order,     except: :index
  resources :contacts, only: [:new, :create]
  resources :bookings, only:[:new, :create, :edit, :index, :show, :update] do
    member do
      get :book_request_accept_confirm
      get :book_request_decline_confirm
    end
  end

  # resources :agency do
  resources :events, only: [:new, :create, :edit, :index, :show, :update] do
    resources :event_locations, only: [:new, :create, :update]
    resources :conversations, only:[:index]
  end
  delete "/events/:id", to: "events#destroy", as: "delete_event"
  get 'events/shortList', to: 'events#shortList'
  get 'new_event_session', to: 'events#new_event_session'

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
  get 'contacts' => 'contacts#new'
  post 'contacts' => 'contacts#create'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  #Ambassador Dashboard
  get 'dashboard', to: 'dashboard#index'
  post 'dashboard/cancel_booking', to: 'dashboard#cancel_booking', as: :cancel_booking

  #Ambassador Busy Shifts
  get 'busyShifts', to:'busy_shift#index'
  get 'busyShifts/new', to: 'busy_shift#new', as: 'new_busy_shift'
  post 'busyShifts', to: 'busy_shift#create', as: 'busy_shifts'
  get 'busyShifts/:id/edit', to: 'busy_shift#edit', as: 'edit_busy_shifts'
  patch 'busyShift/:id', to: 'busy_shift#update'
  delete 'busyShift/:id', to: 'busy_shift#destroy'

  #Creating Shifts and Roles from Event Dates
  get 'roleTypes/', to: 'shifts_role#roleTypes'
  get 'roleStatusList/', to: 'shifts_role#roleStatusList'
  get 'shiftsByDate/', to: 'shifts_role#shiftsByDate'
  get 'rolesByShift/', to: 'shifts_role#rolesByShift'
  post 'shifts/create', to: 'shifts_role#createShift'
  post 'shifts/createRole', to: 'shifts_role#createRoleForShift'
  patch 'shifts/role/:role_id', to: 'shifts_role#changeRoleForShift'
  delete 'shifts/:shift_id', to: 'shifts_role#destroyShift'
  delete 'roles/:role_id', to: 'shifts_role#destroyRole'

  patch 'shortList/add', to: 'shifts_role#shortList'
  delete 'shortList/removeAmbassador', to: 'shifts_role#remove_ambassador_from_short_list'

  get 'shortList/book', to: 'short_lists#submit'

  #Event Dates
  get 'eventDate', to: 'event_dates#datesByLocation'
  get 'eventDate/shifts', to: 'event_dates#shiftsByDateId'
  get 'eventDate/new', to: 'event_dates#new', as: 'new_event_dates'
  post 'eventDate/create', to: 'event_dates#create', as: 'event_dates'
  patch 'eventDate/:id', to: 'event_dates#update'
  delete 'eventDate/id', to: 'event_dates#destroy'

  #Fake Filter Query
  get 'test', to: 'filter_ambassadors#test'
  get 'filterAmbassadors/', to: 'filter_ambassadors#filter'
  get 'filterAmbassadorsIndex/', to: 'filter_ambassadors#filter_index'
  get 'filterForRole/', to: 'filter_ambassadors#fitler_by_role'
  get 'getShortListedAmbassadors/', to: 'filter_ambassadors#short_listed_ambassadors'

  namespace :api, defaults: {format: :json} do
    resources :events, only: [:update, :new, :index, :create, :show, :destroy]
    resources :event_locations, only: [:create, :new, :update, :index, :show, :destroy]
    resources :event_dates, only: [:create, :new, :update, :index, :show, :destroy]
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
	has_one :order

	def add_ambassador(ambassador_id)
		current_item = line_items.find_by(ambassador_id: ambassador_id)
		if current_item
		  current_item.quantity += 1
		else
		  current_item = line_items.build(ambassador_id: ambassador_id)
		end
	  current_item
	end

	def subtotal
		line_items.to_a.sum { |item| item.total_price }
		# sub_total + service_fee
	end


	def service_fee
		subtotal * 0.05
		# line_items.to_a.sum { |item| item.total_price }
	end

	def total_price
		# line_items.to_a.sum { |item| item.total_price }
		service_fee + subtotal
	end

end

app/controllers/carts_controller.rb
class CartsController < SessionsController
  before_action :authenticate_agency!
	before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

	def show
	end

	def index
		@carts = Cart.all
	end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

		respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json`
  def update

		for i in 0..@cart.line_items.count-1 do
			@line_item = LineItem.find(params[:line_item_ids][i])
			@line_item.update_attribute(:quantity, params[:quantity][i])
		end

		redirect_to @cart

		# respond_to do |format|
    #   if @cart.update(cart_params)
    #     format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @cart }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @cart.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Your cart is currently empty' }
      format.json { head :no_content }
    end
  end


	def some_action
	end

	 private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def cart_params
      params[:cart]
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to ambassadors_url, notice: 'Invalid cart'
    end


end

app/views/carts/_cart.html.erb
<table class='table table-striped'>
	<tr>
  	<th class="col-sm-5">Name</th>
  	<th class="col-sm-2 text-center">Rate</th>
  	<th class="col-sm-2 text-center">Hours</th>
  	<th class="col-sm-2 text-center">Amount</th>
  </tr>
  <% @cart.line_items.each do |line_item| %>
	<tr>
		<td class="col-sm-5"><%= line_item.ambassador.first_name %> <%= line_item.ambassador.last_name %></td>
		<td class="col-sm-2 text-center"><%= line_item.ambassador.rate %></td>
		<td class="col-sm-2 text-center">
			<%= line_item.quantity %>
		</td>
		<td class="col-sm-2 text-center"><%= number_to_currency(line_item.total_price) %></td>
	</tr>
	<% end %>

</table>

app/views/carts/show.html.erb
<div class="booking">
	<div class="background">
		<div class="content row ">
			<h2>Review Your Bookings</h2>
			<!-- <%= render @cart %> -->
			<%= form_for(@cart) do |f| %>
			<table class='table table-striped'>
				<tr>
					<th class="col-sm-1">Image</th>
					<th class="col-sm-4">Name</th>
					<th class="col-sm-2 text-center">Rate</th>
					<th class="col-sm-2 text-center">Hours</th>
					<th class="col-sm-2 text-center">Amount</th>
					<th class="col-sm-1 text-center">Remove</th>
				</tr>

				<% for i in 0..@cart.line_items.count-1 do %>
					<%= f.fields_for(@cart.line_items[i]) do |l| %>
						<tr>
							<% line_item = @cart.line_items[i] %>
							<%= hidden_field_tag "line_item_ids[]", line_item.id %>
							<% ambassador = line_item.ambassador %>
							
							<td class="col-sm-3"><%= link_to attachment_image_tag(ambassador.profile_photo, :file, :fill, 50, 50, class: 'img-responsive img-rounded text-center'), ambassador%>	</td>
							<td class="col-sm-2"><%= ambassador.first_name %> <%= ambassador.last_name %></td>
							<td class="col-sm-2 text-center"><%= ambassador.rate %></td>
							<td class="col-sm-1 text-center">
								<%= select_tag('quantity[]', options_for_select((0..40), selected:line_item.quantity), width: "20px" )%>
							</td>
							<td class="col-sm-3 text-center"><%= number_to_currency(line_item.total_price) %></td>
							<td class="col-sm-1 text-center">
								<%= link_to line_item, method: :delete, data: { confirm: 'Are you sure?' } do %>
									<span class="glyphicon glyphicon-trash"></span>
								<% end %>
							</td>
						</tr>
					<% end %>
				<% end %>
		</table>
			<div class="row">
				<div class="col-sm-8">
					<%= link_to "Browse", ambassadors_path, method: :get, class: 'btn btn-lg', id: 'how-btn' %>
				</div>
				<div class="col-sm-4">
					<%= f.button "Update", name: :commit, value: "Update", class: 'btn btn-lg float-right', id: 'how-btn', data: { disable_with: "Updating..." } %>
				<% end %>

					<%= link_to "Next", new_order_path, method: :get, class: 'btn btn-lg', id: 'how-btn', data: { disable_with: "Requesting..." } %>
				<!--<%= button_to 'Clear All', @cart, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm', id: 'ambassador-btn'%> -->
				</div>
			</div>
		</div>
	</div>
</div>